export const ADD_USER = 'ADD_USER'
export const DELETE_USER = 'DELETE_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const SET_USERS = 'SET_USERS'
export const SET_USERS_WITH_QUERY = 'SET_USERS_WITH_QUERY'
